services:
  - type: web
    name: kv-barpeta-admission-portal
    env: python
    plan: free
    buildCommand: bash ./scripts/render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
